import {
  LockMapProject,
  LockMappingConflict,
  ImplementationCard,
} from '../types/lockmap';
import { buildInputSignature } from './lockMappingRules';

const RISK_ICON: Record<string, string> = {
  high: '[HIGH]',
  medium: '[MEDIUM]',
  low: '[LOW]',
};

export function exportToMarkdown(
  project: LockMapProject,
  conflicts: LockMappingConflict[],
  cards: ImplementationCard[]
): string {
  const lines: string[] = [];

  lines.push(`# Locks — Risk Audit Report`);
  lines.push(`\n**Project:** ${project.title}`);
  lines.push(`**Theme:** ${project.theme}`);
  lines.push(`**Tone:** ${project.tone}`);
  lines.push(`**Room Structure:** ${project.roomStructure}`);
  lines.push(`**Target Audience:** ${project.targetAudience}`);
  lines.push(`**Design Stage:** ${project.designStage}`);
  lines.push(`\n---\n`);

  lines.push(`## Zones / Access Timeline\n`);
  for (const zone of project.zones) {
    lines.push(`### ${zone.name}`);
    lines.push(`- **Accessible Stage:** ${zone.accessibleStage}`);
    lines.push(`- ${zone.description}`);
    lines.push('');
  }

  lines.push(`---\n`);
  lines.push(`## Lock Inventory\n`);
  for (const lock of project.locks) {
    lines.push(`### ${lock.label}`);
    lines.push(`- **Input Signature:** \`${buildInputSignature(lock)}\``);
    lines.push(`- **Visible At Stage:** ${lock.visibleAtStage}`);
    lines.push(`- **Physical Description:** ${lock.physicalDescription}`);
    lines.push(`- **Current Theme Treatment:** ${lock.currentThemeTreatment}`);
    lines.push(`- **Reset Identifier:** \`${lock.resetIdentifier}\``);
    lines.push(`- **Accessibility Notes:** ${lock.accessibilityNotes}`);
    lines.push('');
  }

  lines.push(`---\n`);
  lines.push(`## Puzzle Matrix\n`);
  for (const puzzle of project.puzzles) {
    const intendedLock = project.locks.find((l) => l.id === puzzle.intendedLockId);
    lines.push(`### ${puzzle.title}`);
    lines.push(`- **Reveal Stage:** ${puzzle.revealStage}`);
    lines.push(`- **Solution Type:** \`${puzzle.solutionType}${puzzle.solutionLength ? `-${puzzle.solutionLength}` : ''}\``);
    lines.push(`- **Answer Example:** \`${puzzle.answerExample}\``);
    lines.push(`- **Intended Lock:** ${intendedLock?.label ?? puzzle.intendedLockId}`);
    lines.push(`- **Narrative Context:** ${puzzle.narrativeContext}`);
    lines.push('');
  }

  lines.push(`---\n`);
  lines.push(`## Risk Audit\n`);

  const high = conflicts.filter((c) => c.riskLevel === 'high');
  const medium = conflicts.filter((c) => c.riskLevel === 'medium');
  const low = conflicts.filter((c) => c.riskLevel === 'low');

  lines.push(`**Total Conflicts:** ${conflicts.length} (${high.length} high, ${medium.length} medium, ${low.length} low)\n`);

  for (const conflict of conflicts) {
    lines.push(`### ${RISK_ICON[conflict.riskLevel]} — Input Signature \`${conflict.inputSignature}\` at ${conflict.stage}`);
    lines.push(`**Affected Locks:** ${conflict.affectedLockIds.map((id) => project.locks.find((l) => l.id === id)?.label ?? id).join(', ')}`);
    if (conflict.affectedPuzzleIds.length > 0) {
      lines.push(`**Affected Puzzles:** ${conflict.affectedPuzzleIds.map((id) => project.puzzles.find((p) => p.id === id)?.title ?? id).join(', ')}`);
    }
    lines.push(`\n**Diagnosis:** ${conflict.diagnosis}`);
    lines.push(`\n**Recommended Fix:** ${conflict.recommendedFix}`);
    lines.push('');
  }

  lines.push(`---\n`);
  lines.push(`## Theme Implementation Cards\n`);

  for (const card of cards) {
    const lock = project.locks.find((l) => l.id === card.linkedLockId);
    const puzzle = card.linkedPuzzleId
      ? project.puzzles.find((p) => p.id === card.linkedPuzzleId)
      : undefined;
    lines.push(`### ${card.title}`);
    lines.push(`- **Cue Type:** ${card.cueType.replace(/-/g, ' ')}`);
    lines.push(`- **Linked Lock:** ${lock?.label ?? card.linkedLockId}`);
    if (puzzle) lines.push(`- **Linked Puzzle:** ${puzzle.title}`);
    lines.push(`\n**Theme Idea:** ${card.themeIdea}`);
    lines.push(`\n**Build Notes:** ${card.buildNotes}`);
    lines.push(`\n**Player Inference:** ${card.playerInference}`);
    lines.push(`\n**Accessibility Note:** ${card.accessibilityNote}`);
    lines.push(`\n**Reset Note:** ${card.resetNote}`);
    lines.push(`\n**Operator Risk Reduced:** ${card.operatorRiskReduced}`);
    lines.push('');
  }

  lines.push(`---\n`);
  lines.push(`*Generated by Locks — ImmersiveKit*`);

  return lines.join('\n');
}
